# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Protected Utility Program
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown

sass:
  style: compressed

# Build settings
exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - package.json
  - README.md
  - assets/sass
  - vendor
  - manifest-*.yml
  - Staticfile
  - .jekyll-cache
  - .git

# Plugin settings
plugins:
   - jekyll-last-modified-at
   - jekyll-spaceship

jekyll-spaceship:
  processors:
      - table-processor
