# Welcome to Jekyll!
#

# Site settings
title: Protected Utility
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown

sass:
  style: compressed

timezone: Australia/Sydney

# Build settings
exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - package.json
  - CHANGELOG.md
  - README.md
  - LICENSE.md
  - assets/sass
  - vendor
  - manifest-*.yml
  - Staticfile
  - .jekyll-cache
  - .git

# Plugin settings
plugins:
   - jekyll-last-modified-at
